tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "python@3.9"
brew "glib"
brew "cmake"
brew "gnutls"
brew "harfbuzz"
brew "little-cms2"
brew "ffmpeg"
brew "firebase-cli"
brew "git"
brew "python@3.10"
brew "glances"
brew "httpd", restart_service: true
brew "pango"
brew "librsvg"
brew "mysql", restart_service: true
brew "php", restart_service: true
brew "python-tk@3.9"
brew "r"
cask "mactex"
brew "zsh"
