tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "python@3.9"
brew "mysql", restart_service: true
brew "r"
cask "microsoft-teams"
cask "rstudio"
cask "slack"
cask "visual-studio-code"
